#!/bin/bash

set -euo pipefail

# Generated by harwise
# Date: 2025-09-18T18:02:52.224Z
# Samples: 2

# Request 1: GET https://api.example.com/v1/users??limit=10&sort=name
# Original timing: 150ms, size: 512 bytes
curl "https://api.example.com/v1/users??limit=10&sort=name" \
  -H "authorization: [MASKED]" \
  -H "content-type: application/json" \
  -w "\nTime: %{time_total}s\nSize: %{size_download} bytes\nStatus: %{http_code}\n"

# Request 2: POST https://api.example.com/v1/login
# Original timing: 200ms, size: 256 bytes
curl -X POST "https://api.example.com/v1/login" \
  -H "content-type: application/json" \
  -d '{"username": "user", "password": "pass"}' \
  -w "\nTime: %{time_total}s\nSize: %{size_download} bytes\nStatus: %{http_code}\n"

